version: '3.8'

services:
  php-8.3-fpm:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: symfony_php
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/conf.d:/usr/local/etc/php/conf.d
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - /home:/home
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    ports:
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: symfony_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 1s
      retries: 5
      start_period: 60s
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx:/etc/nginx/conf.d
    ports:
      - "8180:80"
    depends_on:
      - php-8.3-fpm

volumes:
  database_data:
